import {
  ApiError,
  createApi,
  createApiClient,
  createAuthResource,
  createBillingResource,
  createChatResource,
  createFriendResource,
  createPlaylistResource,
  createRoomBotResource,
  createRoomBotRealtimeClient,
  createRoomResource,
  createSettingsResource,
  createShopResource,
  createSourceResource,
  createSystemResource,
  createUserResource,
  parseRoomQueueSnapshot,
  WavezApi,
} from "@wavezfm/api";
import { createApiCalls } from "./api/index.js";

export const WAVEZ_API_CAPABILITIES = Object.freeze({
  authModes: ["session", "auth-token", "room-bot", "none"],
  locales: ["en", "pt-BR"],
  tokenManagement: {
    api: [
      "setAuthToken(token)",
      "getAuthToken()",
      "setRoomBotToken(token)",
      "getRoomBotToken()",
    ],
    sdk: [
      "setAuthToken(token)",
      "getAuthToken()",
      "setRoomBotToken(token)",
      "getRoomBotToken()",
    ],
  },
  errorHandling: {
    errorClass: "ApiError",
    fields: ["message", "status", "code", "response"],
  },
  treeShaking: {
    supported: true,
    importPaths: [
      "@wavezfm/api",
      "@wavezfm/api/resources/auth",
      "@wavezfm/api/resources/settings",
      "@wavezfm/api/resources/user",
      "@wavezfm/api/resources/room",
      "@wavezfm/api/resources/playlist",
      "@wavezfm/api/resources/source",
      "@wavezfm/api/resources/chat",
      "@wavezfm/api/resources/friend",
      "@wavezfm/api/resources/shop",
      "@wavezfm/api/resources/billing",
      "@wavezfm/api/resources/system",
      "@wavezfm/api/resources/room-bot",
      "@wavezfm/api/realtime/room-bot",
      "@wavezfm/api/types",
    ],
  },
  typescript: {
    examples: [
      "AuthUser",
      "RoomSummary",
      "PlaylistTrack",
      "MediaSearchResult",
      "ChatMessage",
      "RoomBotState",
      "WsPacket",
    ],
    source: "@wavezfm/api",
  },
  resources: {
    auth: [
      "login",
      "register",
      "me",
      "getPendingTwoFactor",
      "sendPendingTwoFactorCode",
      "verifyPendingTwoFactor",
      "getTwoFactorStatus",
    ],
    settings: [
      "get",
      "update",
      "getTwoFactor",
      "sendPhoneVerification",
      "verifyPhoneNumber",
      "startEmailTwoFactor",
      "startSmsTwoFactor",
      "verifyOtpTwoFactor",
      "startAuthenticatorTwoFactor",
      "verifyAuthenticatorTwoFactor",
      "disableTwoFactor",
    ],
    user: ["getById", "getByUsername", "getBadges", "listAllBadges"],
    room: [
      "list",
      "featured",
      "getBySlug",
      "getJoinPreview",
      "getWaitlist",
      "getQueueStatus",
      "create",
      "join",
      "favorite",
      "unfavorite",
      "getManagement",
      "createBotToken",
      "listEmojis",
      "listAuditLogs",
      "updateSettings",
      "updateLinkFilters",
      "setRole",
      "setQueueAccess",
      "unban",
      "createEmoji",
      "updateEmoji",
      "deleteEmoji",
    ],
    playlist: [
      "list",
      "create",
      "update",
      "remove",
      "getTracks",
      "previewUrl",
      "addTrack",
      "reorderTracks",
      "removeTrack",
      "listImports",
      "getImport",
      "startSpotifyImport",
      "importYouTubePlaylist",
      "importSoundCloudPlaylist",
      "cancelImport",
      "searchPreview",
    ],
    source: ["search", "searchYouTube", "searchSoundCloud", "searchAll"],
    chat: [
      "getMessages",
      "getMessagesBySlug",
      "deleteMessage",
      "updateMessage",
      "pinMessage",
      "clearPinnedMessage",
      "clearChat",
    ],
    friend: [
      "list",
      "pending",
      "sendRequest",
      "acceptRequest",
      "rejectRequest",
      "remove",
      "follow",
      "unfollow",
      "followers",
      "following",
    ],
    shop: ["getCatalog", "getWallet", "purchase", "equip", "getInventory"],
    billing: [
      "createSubscriptionCheckout",
      "createDiamondCheckout",
      "createRoomDonationCheckout",
      "createGlobalDonationCheckout",
      "createDiamondGiftCheckout",
      "createSubscriptionGiftCheckout",
      "listPendingGifts",
      "markGiftSeen",
    ],
    system: ["status", "publicStats", "health"],
    roomBot: [
      "getState",
      "getQueueStatus",
      "getMessages",
      "sendMessage",
      "deleteMessage",
      "pinMessage",
      "clearPinnedMessage",
      "clearChat",
      "getManagement",
      "listEmojis",
      "listAuditLogs",
      "updateSettings",
      "updateLinkFilters",
      "setRole",
      "setQueueAccess",
      "unban",
      "createEmoji",
      "updateEmoji",
      "deleteEmoji",
    ],
  },
  roomBotPermissions: [
    "read_state",
    "read_chat",
    "send_chat",
    "manage_queue",
    "skip_others",
    "mute_user",
    "kick_user",
    "ban_user",
    "clear_chat",
    "manage_room",
  ],
  realtime: {
    commands: [
      "join_room",
      "leave_room",
      "ping",
      "send_chat",
      "skip",
      "remove_from_queue",
      "reorder_queue",
      "mute_user",
      "kick_user",
      "ban_user",
    ],
    clientEvents: ["open", "close", "connected", "socket_error", "packet"],
    roomEvents: [
      "message_created",
      "message_updated",
      "message_deleted",
      "chat_cleared",
      "track_started",
      "track_skipped",
      "track_paused",
      "track_resumed",
      "room_state_snapshot",
      "waitlist_update",
      "waitlist_join",
      "waitlist_leave",
      "queue_reordered",
      "votes_snapshot",
      "track_grabbed",
      "user_joined",
      "user_left",
      "user_kicked",
      "user_banned",
      "user_role_updated",
      "user_updated",
      "pong",
      "error",
    ],
  },
  notes: [
    "Rotas de usuario/sessao sao browser-first e dependem de cookie/session.",
    "Rotas roomBot sao as mais adequadas para backend e automacao.",
    "Nao existe voto de track exposto para bots no SDK atual.",
    "O backend nao interpreta prefixo de comando do bot automaticamente.",
    "O helper realtime espera WebSocket nativo ou websocketFactory customizado.",
  ],
});

function resolveRealtimeOptions(config, options) {
  const roomBotToken = options.botToken ?? config.roomBotToken ?? null;
  if (!roomBotToken) {
    throw new Error(
      "Room bot token is required to create the realtime client. Pass botToken explicitly or configure roomBotToken.",
    );
  }

  return {
    baseURL: config.baseURL,
    locale: config.locale,
    messages: config.messages,
    logging: config.logging,
    ...options,
    botToken: roomBotToken,
  };
}

export function createWavezSdk(config) {
  const client = createApiClient(config);
  const rest = createApiCalls(client);

  return {
    client,
    api: client.api,
    rest,
    capabilities: WAVEZ_API_CAPABILITIES,
    setAuthToken: (token) => client.api.setAuthToken(token ?? null),
    getAuthToken: () => client.api.getAuthToken(),
    setRoomBotToken: (token) => client.api.setRoomBotToken(token ?? null),
    getRoomBotToken: () => client.api.getRoomBotToken(),
    createRealtime: (options) =>
      createRoomBotRealtimeClient(resolveRealtimeOptions(config, options)),
  };
}

export {
  ApiError,
  WavezApi,
  createApi,
  createApiCalls,
  createApiClient,
  createAuthResource,
  createSettingsResource,
  createUserResource,
  createRoomResource,
  createPlaylistResource,
  createSourceResource,
  createChatResource,
  createFriendResource,
  createShopResource,
  createBillingResource,
  createSystemResource,
  createRoomBotResource,
  createRoomBotRealtimeClient,
  parseRoomQueueSnapshot,
};
